[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "1_1"
path = "src/1_1.rs"

[[bin]]
name = "1_2"
path = "src/1_2.rs"

[[bin]]
name = "3_1"
path = "src/3_1.rs"
